version = 1
SPDX-PackageName = "talk-desktop"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/talk-desktop"

[[annotations]]
path = ["dark-highcontrast.css","dark-highcontrast.plain.css","dark.css","dark.plain.css","light-highcontrast.css","light-highcontrast.plain.css","light.css","light.plain.css","opendyslexic.css"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
